#!/usr/bin/env bash

set -ex

unset GMAP_KEY
unset GMAP_GEOCODING_KEY
unset REDIS_SERVER
unset HTTP_PROXY
unset http_proxy

# for i in $(find ~/gedcoms/* -name \*ged -o -name \*GED); do
# for i in tests/gedcoms/*.ged; do

# Allow spaces in the filenames
find ~/Genealogy/gedcoms -type f -name \*ged -o -name \*GED -print0 | while IFS= read -r -d '' gedcom; do
	rm -rf dynamic-site/data dynamic-site/img static-site/
	perl -MDevel::Hide=Geo::libpostal \
		./ged2site -cFd "$gedcom"
	weblint static-site/*html
	xmllint dynamic-site/data/people.xml > /dev/null
	if [ -r dynamic-site/data/locations.xml ]; then
		xmllint dynamic-site/data/locations.xml > /dev/null
	fi
	grep 'etravel' static-site/*.html && exit 1
	# grep '  ' static-site/*.html && exit 1
	# grep '  ' dynamic-site/data/people.csv && exit 1

	rm -rf dynamic-site/data dynamic-site/img static-site/
	perl -MDevel::Hide=Geo::libpostal \
		./ged2site -cFdwm "$gedcom"
	weblint static-site/*html
	for j in static-site/*.html; do
		echo $j:
		~/src/njh/schema-validator/bin/validate-schema --file "$j" --dynamic
	done
	xmllint dynamic-site/data/people.xml > /dev/null
	if [ -r dynamic-site/data/locations.xml ]; then
		xmllint dynamic-site/data/locations.xml > /dev/null
	fi

	cd dynamic-site/data && ../bin/tosqlite
	cd -
	rm -rf dynamic-site/data dynamic-site/img static-site/
	perl -MDevel::Hide=Geo::libpostal \
		./ged2site "$gedcom"
	weblint static-site/*html
	xmllint dynamic-site/data/people.xml > /dev/null
	if [ -r dynamic-site/data/locations.xml ]; then
		xmllint dynamic-site/data/locations.xml > /dev/null
	fi
	cd dynanic-site && cgi-bin/page.fcgi page=home lint_content=0 && cd ..
done
