#!/usr/bin/env bash

set -ex

unset GMAP_KEY
# for i in ~/gedcoms/*.ged ~/gedcoms/*.GED ~/gedcoms/*/*.ged; do
for i in tests/gedcoms/*.ged; do
	rm -rf dynamic-site/data dynamic-site/img static-site/
	perl -MDevel::Hide=Geo::libpostal \
		./ged2site -cFd "$i"
	weblint static-site/*html
	xmllint dynamic-site/data/people.xml > /dev/null
	if [ -r dynamic-site/data/locations.xml ]; then
		xmllint dynamic-site/data/locations.xml > /dev/null
	fi
	grep 'etravel' static-site/*.html && exit 1
	# grep '  ' static-site/*.html && exit 1
	# grep '  ' dynamic-site/data/people.csv && exit 1
done
