#!/usr/bin/env perl

# Author Nigel Horne: njh@bandsman.co.uk
# Copyright (C) 2017, Nigel Horne

# Usage is subject to licence terms.
# The licence terms of this software are as follows:
# Personal single user, single computer use: GPL2
# All other users (including Commercial, Charity, Educational, Government)
#	must apply in writing for a licence for use from Nigel Horne at the
#	above e-mail.

use warnings;
use strict;
use autodie qw(:all);

use Tk;
use Tk::ExecuteCommand;
use Config::Auto;

my $config = Config::Auto::parse();

my $mw = MainWindow->new();

my $menubar = $mw->Menu(-type => 'menubar');
$mw->configure(-menu => $menubar);

my $f = $menubar->cascade(-label => '~File', -tearoff => 0);
$f->command(-label => 'Generate ...', -command => sub { file_open() });
$f->command(-label => 'Exit', -command => sub { exit(0) });

MainLoop();

sub file_open
{
	# my $args = @_;
	# $mw->BackTrace("Open: $args");

	my @types = ([ 'Gedcom', '.ged', 'TEXT']);
	my $file = $mw->getOpenFile(
		-filetypes => \@types,
		-defaultextension => '.ged',
		-initialdir => $config->{'initialdir'}
	);

	# FIXME: options should be optional
	my $ec = $mw->ExecuteCommand(
		-command => '',
		-entryWidth => 50,
		-height     => 10,
		-label      => '',
		-text       => 'Execute',
	)->pack();
	$ec->configure(-command => "./ged2site -mcdFw '$file'");
	$ec->execute_command();
	$ec->update();
}
